### ISSUE TITLE
数据下载不了

### ISSUE THREAD

**Issue by webbery** [lzw-all-in/CS224n_assignments#1]
Hi，
可能是因为网络问题，我这边下载不了assignment1的数据集。可以在百度云上共享一下数据集么~  
非常感谢~

**Comment by lzw-all-in** [comment]
> Hi，
> 可能是因为网络问题，我这边下载不了assignment1的数据集。可以在百度云上共享一下数据集么~
> 非常感谢~

抱歉抱歉，今天才看到
所有数据连接https://pan.baidu.com/s/1IXZXzHpm1MO19hl6TwSkcQ
：）

**Comment by webbery** [comment]
非常感谢~
